### ISSUE TITLE
Naming mistake in Keybase.install

### ISSUE THREAD

**Issue by apettinen** [autopkg/tallfunnyjew-recipes#16]
Hi,

Keybase.install recipe fails, as there's a mistake in the naming:
```<key>Input</key>
    <dict>
        <key>NAME</key>
        <string>VLC</string>
    </dict>
```
Might want to change the name to key Keybase instead of VLC. :)

**Comment by gregneagle** [comment]
While I agree that's a silly error that should be fixed, I don't understand how/why that would cause the install recipe to _fail_. NAME should be used for output (how one _names_ the pkg/dmg/Munki item) and should be able to be be changed to _anything_ without causing the recipe to fail. If I want to name the pkg/dmg/Munki item/Jamf item "Booger" it should still _work_.

So if the mistaken name of "VLC" is causing the recipe to fail, there's some other problem with the recipe (or a parent recipe).

**Comment by gregneagle** [comment]
I think the actual issue is here:

https://github.com/autopkg/jaharmi-recipes/blob/master/Keybase/Keybase.download.recipe

```
<dict>
			<key>Arguments</key>
			<dict>
				<key>filename</key>
				<string>%NAME%.dmg</string>
				<key>url</key>
				<string>%PRODUCT_DOWNLOAD_URL%</string>
			</dict>
			<key>Processor</key>
			<string>URLDownloader</string>
		</dict>
```
NAME is used to set the filename of the download, but in subsequent steps in the recipe, the dmg is referred to as "Keybase.dmg". So any name other than "Keybase" will cause the recipe (and any child recipes) to fail. cc @Jaharmi

**Comment by apettinen** [comment]
Yeah, exactly, the actual mistake is in the download recipe. Didn't have time to inform the parent recipe author - should've done it in the first place, sorry about that. :)

**Comment by tallfunnyjew** [comment]
This entire discussion somehow bypassed me, gents. Glad you both caught the issue and addressed the parent recipe. I've changed the installer recipe to name the download correctly and install in the proper location with the proper name. :)
