### ISSUE TITLE
Error on Onyx10.13 recipe

### ISSUE THREAD

**Issue by Darkomen78** [autopkg/tallfunnyjew-recipes#17]
There is a little mistake in your Onyx10.13.download.recipe L8 :
<string>com.github.tallfunnyjew.pkg.Onyx1013</string>
must be
<string>com.github.tallfunnyjew.download.Onyx1013</string>

**Comment by tallfunnyjew** [comment]
great catch. i accidentally uploaded an old recipe into git on my last round of updates. will fix ASAP. thanks for the heads up.

**Comment by tallfunnyjew** [comment]
Fixed and re-uploaded. 
![screenshot 2018-09-11 10 34 46](https://user-images.githubusercontent.com/2782686/45377055-55030b80-b5ae-11e8-8820-f924aeea9a76.png)
