### ISSUE TITLE
VLC-asap: No match found on URL

### ISSUE THREAD

**Issue by flammable** [autopkg/tallfunnyjew-recipes#23]
Hello! I'm using @aysiu's [VLC-asap.munki](https://github.com/autopkg/aysiu-recipes/blob/master/VLC-asap/VLC-asap.munki.recipe) version of this recipe, which relies on your VLC-asap.download recipe.

If I'm reading this correctly, it looks like VLC recently changed the name of their macOS disk images:

```
URLTextSearcher
{'Input': {'re_pattern': '([\\d.]*\\/macosx\\/vlc-[\\d.]*.dmg)',
           'url': 'https://www.videolan.org/vlc/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.videolan.org/vlc/
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
No match found on URL: https://www.videolan.org/vlc/
Failed.
Receipt written to /Users/sjuadmin/Library/AutoPkg/Cache/local.munki.VLC-asap/receipts/local.munki-receipt-20210119-084924.plist

The following recipes failed:
    local.munki.VLC-asap
        Error in local.munki.VLC-asap: Processor: URLTextSearcher: Error: No match found on URL: https://www.videolan.org/vlc/

Nothing downloaded, packaged or imported.
```

The download listed on [VLC's website](https://www.videolan.org/vlc/) is now `https://get.videolan.org/vlc/3.0.12/macosx/vlc-3.0.12-intel64.dmg`, presumably because they are preparing an arm64/universal version for the new Apple Silicon Macs.

Any chance of taking a look at this? Thanks!

Mike

**Comment by aysiu** [comment]
I suspect this may have to splinter into two download recipes, at least until there is a universal binary for VLC:
`([\d.]*\/macosx\/vlc-[\d.]*-intel64.dmg)` and `([\d.]*\/macosx\/vlc-[\d.]*-arm64.dmg)`

I'm inclined to just go with Intel until there is a universal binary, but maybe that's me just being foolishly optimistic that a universal binary will show up in the near future.

@tallfunnyjew , any thoughts?

**Comment by tallfunnyjew** [comment]
i'll have a look and get back to ya! Thanks for bringing it to my attention.

**Comment by tallfunnyjew** [comment]
Yup, looks like multiple versions based on your silicon, so... I'm forking the autopkg recipes to ensure that both builds are available. Thanks for the regex code, BTW. And yeh, I'm not in the business of being optimistic with VLC, so let's see what happens and at least provide folks with what they need, @aysiu

**Comment by aysiu** [comment]
Another option to having two separate recipes would be to have an INPUT that could override Intel but to default to Intel if Silicon isn't specified.

**Comment by aysiu** [comment]
On second thought, lots of admins may want to download both versions, so having separate recipes may make more sense.

**Comment by tallfunnyjew** [comment]
Yeh, I'm always a fan of having multiple streams for different installations. It ain't perfect, but at least it'll organized.

**Comment by homebysix** [comment]
If the only difference between the two VLC download recipes is a URL component, I'd strongly suggest following the example of other AutoPkg recipes like Firefox and Chrome by creating an input variable that admins can use to designate which one they want. Admins who want to download both versions can create two overrides, each with different inputs.

If there is a Universal build available, that should be the default choice (as it's the most widely compatible).

Combining the recipes also ensures that unrelated changes to VLC don't need to be changed in multiple places (complicating PRs and confusing potential contributors).

**Comment by tallfunnyjew** [comment]
was just about to post this question on the autopkg group forum but you've answered my question for me. thanks.
