### ISSUE TITLE
Missing Onyx10.11.munki.recipe

### ISSUE THREAD

**Issue by AndersTao** [autopkg/tallfunnyjew-recipes#3]
Hi

I created the munki recipe for Onyx 10.11, hope this can be added to you repo

https://gist.github.com/AndersTao/3c24a16b9932f051c627

Sorry, know this really not is an issue, but I was unable to make a pull request

**Comment by tallfunnyjew** [comment]
Anders,

Thrilled that you wanted to make a pull request and add functionality. Have no idea how to help you do that as you're the first to ask about a pull request. I'm unclear how to help. If you want to tell me how I call allow for you to make a pull I'm happy to help approve that!

**Comment by AndersTao** [comment]
I have no idea how to do it, sorry, I am new to git and github.. leaning as we go..
Just wanted, to make it easy for you to add my change to your repo ;)

**Comment by tallfunnyjew** [comment]
i've now added munki recipes for all of my Onyx recipes, sir.
